### ISSUE TITLE
debug logging error with Failure object 

### ISSUE THREAD

**Issue by akrherz** [akrherz/pyWWA#18]
Noticed this failure while reviewing logs.  It happens at shutdown time!

```
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] Unhandled Error
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011Traceback (most recent call last):
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/xish/utility.py", line 107, in callback
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    methodwrapper(*args, **kwargs)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/xish/utility.py", line 27, in __call__
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    self.method(*nargs, **nkwargs)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/jabber/xmlstream.py", line 530, in onStreamError
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    STREAM_ERROR_EVENT)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/xish/utility.py", line 317, in dispatch
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    callbacklist.callback(obj)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011--- <exception caught here> ---
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/xish/utility.py", line 107, in callback
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    methodwrapper(*args, **kwargs)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/usr/lib/python2.7/site-packages/twisted/words/xish/utility.py", line 27, in __call__
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    self.method(*nargs, **nkwargs)
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011  File "/home/ldm/pyWWA/parsers/common.py", line 287, in debug
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011    log.msg(elem.toXml().encode('utf-8'))
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] #011exceptions.AttributeError: Failure instance has no attribute 'toXml'
Jul 13 15:23:20 iem12 pyWWA/lsr_parser: [XmlStream,client] SETTING authenticated to false!
```

**Comment by akrherz** [comment]
Does not happen with current code
